name: Publish to Github Packages

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  packages: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      # Yes, this is intentionally run on all pushes, not just releases
      # This makes it easier to make changes during build season
      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Setup Pages
        if: github.event_name == 'release'
        uses: actions/configure-pages@v4
      - name: Upload Javadoc artifact
        if: github.event_name == 'release'
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./build/docs/javadoc"
      - name: Deploy Javadoc to GitHub Pages
        if: github.event_name == 'release'
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Mark as latest
        if: github.event_name == 'release'
        run: |
          gh api --method PATCH -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${{ github.repository }}/releases/${{ github.event.release.id }} -f make_latest=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
